nome = input('Digite seu Nome: ')
print('Seja Bem-Vindo,', nome!)
pergunta = input('Você deseja virar um Hacker?: ')
print('Entendi, então a resposta é:,', pergunta')
print('Bem, você irá ficar querendo ser, vai tomar no cúkkk!')
